### ISSUE TITLE
Docusaurus V3 issue

### ISSUE THREAD

**Issue by Chesterguan** [chorus-ai/Chorus_SOP#1]
- [x] V3 SSR compatible issue
- [x] Change the navigatorBanner and generate the sidebar for each tab

Expected due date :  Mar 27th, 2024

**Comment by jshoughtaling** [comment]
@Chesterguan - just wanted to follow up on this issue. Is there anything I can do to help push it forward?

**Comment by jshoughtaling** [comment]
I will handle the re-organization of the website (adding elements to the top banner/etc.). Closing this issue as fixed now that the site is published.
