### ISSUE TITLE
Issue Body in Each SOP Document Issue Requires Detailed Specifications

### ISSUE THREAD

**Issue by jshoughtaling** [chorus-ai/Chorus_SOP#26]
Each `[SOP Document]...` issue should contain details about the content that is expected to be provided as part of that SOP. Currently, these issue bodies are mostly empty, but @CmCC1435 has information that she can use to update them accordingly.

It is critical that each SOP is properly specified in order to:
1. Assist the SOP author(s) in creating documents with an appropriate scope
2. Assist the SOP reviewer(s) in evaluating whether the contents sufficiently cover the requested information

**Comment by CmCC1435** [comment]
Items have been entered on what should be considered for the issues that I do have. Those can add more if needed.
