### ISSUE TITLE
[SOP Document] Data Requests

### ISSUE THREAD

**Issue by jshoughtaling** [chorus-ai/Chorus_SOP#6]

**Comment by clermontg** [comment]
Jared,
what is the action item? Is it to fill in the SOP template provided and upload it in this box?

**Comment by jshoughtaling** [comment]
Hey @clermontg - I wrote up a small section for how to contribute your SOP in the [README](https://github.com/chorus-ai/Chorus_SOP?tab=readme-ov-file#how-to-contribute-to-the-sop-documentation). If you'd prefer, you can send me your draft of the SOP and I can place it in a pull request for review?

@CmCC1435 - I believe you were going to add descriptions to each of the SOP issues about what they're expected to contain based on prior conversations where they were defined?

**Comment by CmCC1435** [comment]
Yes I plan on working on it today. We are reviewing one SOP today but if we have time I can see if we can review your SOP today too.

________________________________

**Comment by CmCC1435** [comment]
Items to be considered to include:
- Reporting timelines
- Required data
